apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openclaw
  labels:
    app.kubernetes.io/name: pinchy-openclaw
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.openclaw.service.port }}
      targetPort: gateway
      name: gateway
  selector:
    app.kubernetes.io/name: pinchy-openclaw
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
